### PR TITLE
Add people page

### PR DESCRIPTION
**Pull request by pderakhshanfar**

### CODE REVIEW

**Comment by vovak** [comment]
hi, thank you for the pull request — the page looks really nice. 

It however needs another pass.
1. Please check spelling: there are typos. "Adminstrator" is one example I could spot.
2. The titles could look more consistent. Both within the page — currently, it uses both "Track lead" and "Track Lead", "PhD Student" and "PhD Researcher"; with the internal representation at JetBrains as well (see Researcher / Student; Administrator / Lead).
3. It would be great to have a way to easily distinguish JetBrains folks from TU Delft folks.

It would also be awesome to display the people involved in individual track pages, like we do for news and publications.

**Comment by pderakhshanfar** [comment]
@vovak, can you please check again?

**Comment by vovak** [comment]
hi, thanks!
The consistency issue is still there though: see the titles of the two Egors for the example.

**Comment by pderakhshanfar** [comment]
Sorry! It is fixed now.

**Pull request merged**
